name: Ktlint check workflow

on:
  workflow_call:
jobs:
  ktlintCheck:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check format
        run: |
          chmod +x gradlew
          ./gradlew ktlintCheck
        with:
          args: >
            -Dsonar.gradle.skipCompile=true