name: Main project workflow

on:
  push:
    branches:
      - main
      - develop
jobs:

  sonarcloud:
    name: SonarCloud
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'temurin'
      - name: SonarQube Scan
        run: |
            chmod +x gradlew
            ./gradlew build sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  test:
    needs:
      - ktlintCheck
    name: test kotlin
    uses: ./.github/workflows/kotlin_test_pipeline.yml