name: Main project workflow

on:
  push:
    branches:
      - main
      - develop
jobs:

  sonar:
    name: SonarQube Scan
    run: |
          chmod +x gradlew
          ./gradlew build sonar
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/ktlint_check_pipeline.yml

  test:
    needs:
      - ktlintCheck
    name: test kotlin
    uses: ./.github/workflows/kotlin_test_pipeline.yml